[build]
  command = "npm run build"
  publish = "out"  # ✅ this must be "out" since output: export puts static files there

[[plugins]]
  package = "@netlify/plugin-emails"

[functions]
  node_bundler = "esbuild"

[env]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"  # ✅ skip the old Next plugin
